### ISSUE TITLE
SVG Widget

### ISSUE THREAD

**Issue by benedictwagnall** [willrogers/project-react#22]
- [x] - Make an SVG widget to compare ease-of-use/efficiency with canvas

**Comment by benedictwagnall** [comment]
From SO: 

"...SVG on the other hand must maintain references to each object that it renders. Every SVG/VML element you create is a real element in the DOM. By default this allows you to keep much better track of the elements you create and makes dealing with things like mouse events easier by default, but it slows down significantly when there are a large number of objects.
   Those SVG DOM references mean that some of the footwork of dealing with the things you draw is done for you. And **SVG is faster when rendering really large objects, but slower when rendering many objects**..."

Maybe we should use an SVG if we decide to make any heat maps or complex graphs.

**Comment by willrogers** [comment]
Can you include a link to the SO question?

**Comment by benedictwagnall** [comment]
[Here](https://stackoverflow.com/questions/5882716/html5-canvas-vs-svg-vs-div)

**Comment by benedictwagnall** [comment]
SVG seems to be pretty powerful, but as a result the syntax is fairly complex, at least for me as I need to refresh my (old) knowledge of geometry - learning a bit about it now.
